# Generated by Django 5.0.8 on 2024-08-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessId', models.IntegerField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(blank=True, max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('totalStorage', models.CharField(blank=True, max_length=100)),
                ('remainingStorage', models.CharField(blank=True, max_length=100)),
                ('expirationDate', models.DateTimeField()),
                ('package', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBusinessFolder',
            fields=[
                ('isDeleted', models.BooleanField(default=False)),
                ('permanentDelete', models.BooleanField(default=False)),
                ('permanentDeletedOn', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('folderId', models.AutoField(primary_key=True, serialize=False)),
                ('folderName', models.CharField(blank=True, max_length=100)),
                ('folderPath', models.CharField(blank=True, max_length=100)),
                ('blobFolderName', models.CharField(blank=True, max_length=100)),
                ('blobFolderPath', models.CharField(blank=True, max_length=100)),
                ('folderParentId', models.CharField(blank=True, max_length=100)),
                ('ownerId', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField(blank=True, default=0)),
                ('folderType', models.CharField(blank=True, max_length=100)),
                ('isPublic', models.BooleanField(default=False)),
                ('isLocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentBusinessFile',
            fields=[
                ('isDeleted', models.BooleanField(default=False)),
                ('permanentDelete', models.BooleanField(default=False)),
                ('permanentDeletedOn', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(blank=True, max_length=100)),
                ('filePath', models.CharField(blank=True, max_length=100)),
                ('blobFileName', models.CharField(blank=True, max_length=100)),
                ('blobFilePath', models.CharField(blank=True, max_length=100)),
                ('ownerId', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('isPublic', models.BooleanField(default=False)),
                ('isReadOnly', models.BooleanField(default=False)),
                ('fileUrl', models.CharField(blank=True, max_length=500)),
                ('folderId', models.ForeignKey(db_column='folderId', on_delete=django.db.models.deletion.CASCADE, to='documentBusinessService.documentbusinessfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubBusiness',
            fields=[
                ('subBusinessId', models.IntegerField(primary_key=True, serialize=False)),
                ('subBusinessName', models.CharField(blank=True, max_length=100)),
                ('accessOf', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('businessId', models.ForeignKey(db_column='businessId', on_delete=django.db.models.deletion.CASCADE, to='documentBusinessService.business')),
            ],
        ),
    ]
